fix: update Claude format_function_call_results logic (#3758)
- We were seeing `TypeError: Claude.format_function_call_results()
missing 1 required positional argument: 'tool_ids'
`
- But `tool_ids` is not used in Claude's
`format_function_call_results()`. This PR removes that param and fixes
the error